package org.example.protocol;

public enum MessageType {
    LOGIN, REGISTER, LOGOUT,
    TEXT, USER_LIST, FILE_TRANSFER,
    LOAD_CONTACTS, CONTACTS_RESPONSE,
    LOAD_HISTORY, HISTORY_RESPONSE,
    LOAD_CALL_HISTORY, CALL_HISTORY_RESPONSE,
    LOAD_CALL_HISTORY_ALL, CALL_HISTORY_ALL_RESPONSE,
    CALL_REQUEST, CALL_ACCEPT, CALL_REJECT, CALL_END,
    AUDIO_PORT_REGISTER, VIDEO_PORT_REGISTER,
    // Groupes V2
    GROUP_CREATE, GROUP_ADD_MEMBER, GROUP_REMOVE_MEMBER,
    GROUP_MESSAGE, GROUP_LIST,
    LOAD_GROUP_HISTORY, GROUP_HISTORY_RESPONSE,
    // Réunions V2
    MEETING_START, MEETING_JOIN, MEETING_LEAVE,
    DELETE_MESSAGE,
    ERROR, INFO
}
